name: Static Analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: refactor and static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Refactor Code Analysis
        run: ./vendor/bin/rector process --dry-run

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --error-format=github